spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: create-drop # create, create-drop, update, validate, none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    platform: 'postgres'
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: 123

server:
  port: 8080

swagger:
  enabled: true
  host: ${SWAGGER_HOST}
  path:




